using PrismExtensionServices.Shared.Serialization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace PrismExtensionServices.Shared.Prism;

public partial class Invoice
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_sale_used_points_negative;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_perc3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? send_sale_last_error;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? activity2_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? ship_method_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? order_ship_method_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee3_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? used_shipping_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? employee1_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? ref_sale_sid;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? refSaleCashier;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? refSaleEmpl1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? refSaleEmpl2;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? refOrderCashier;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? refOrderEmpl1;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee3_full_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom8;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? so_cancel_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? fee_tax_included3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_string2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area2_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_trans_disc_amt_used;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf6;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? eft_invoice_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? over_tax_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? notes_general;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_perc5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? fee_type4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_amt5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_address_line3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? lty_item_gift_pgm_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_tax2_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? original_store_uid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_order_used_points_positive;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? detax_flag_manually;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? ref_order_doc_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_subtotal_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? refund_document_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? udf_float2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? order_status;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf11;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? hist_discount_reason4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? st_primary;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? subsidiary_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? has_return;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_fee_amt1_bdt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_amt1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_quantity_filled;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf17;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_lvl_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? so_deposit_amt_paid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? elapsed_time;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_amt1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? till_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string?    ship_method;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_string5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_gift_card;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_amt_no_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? ref_sale_created_datetime;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? order_due_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? return_qty;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_fee_amt1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee1_login_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string?    st_udf3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? used_subtotal;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? used_fee_amt1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? gl_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? fee_type5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf16;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee3_login_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom7;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? return_total_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf12;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? employee5_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? lty_perc_reward_pgm_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? ref_sale_doc_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? notes_order;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_tax_percentage;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<InvoiceItem>? items;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? due_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_total_redeem_pgm_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_balance_for_item_redeem;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf8;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? shipping_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf9;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_fulfilling_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_info;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf14;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_address_line2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_info;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ref_order_tax_area_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? detax_amount;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? lty_total_redeem_pgm_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ship_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_subtotal;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? activity4_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? custom_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? rounding_offset;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf17;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? st_price_lvl;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? has_sale;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? row_version;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? bt_price_lvl;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf7;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? deposit_amt_required;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? order_fee_type1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? order_ship_method;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? bt_cuid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? fee_name3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string?    manual_disc_reason;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? fee_name5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? till_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_tax_area2_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? createdby_employeeid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf10;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? bt_detax_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? send_sale_status;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? employee3_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_used_points;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee5_full_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? subsidiary_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? controller_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? fee_name1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? employee2_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_alternate_id1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_debit_card;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom9;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_address_line1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_phone1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? order_shipping_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? manual_disc_value;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_tax_area_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? ship_priority;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_sale_earned_points_positive;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_country;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_countryname;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_perc_reward_disc_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? discount_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? hist_discount_reason2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_address_line3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf15;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_sale_earned_points_negative;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? price_lvl;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_address_line6;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? modifiedby_employeeid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_amt_manual_bdt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf14;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_amt_manual_used;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_order_used_points_negative;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_redeem_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_total_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? so_deposit_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom0;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? ship_method_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? created_datetime;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_amt3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? pos_flag3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? order_changed_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_gift_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_subtotal_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_date3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_address_line4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? workstation_uid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? total_deposit_taken;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? tracking_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? cashier_full_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_string4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? receipt_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_rebate_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? document_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? tenant_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? discount_perc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? fee_tax_included1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? modified_datetime;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_email;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_subtotal;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_tax_area_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? archived;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area_order_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? used_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? bt_primary;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_discount_perc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_clob1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? store_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee4_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_percentage;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<InvoiceTender>? tenders;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_address_line5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_perc2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? shipping_tax_included;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? notes_lostdoc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? delete_discount;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? exchange_qty;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_phone2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee1_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? promo_gd_modifiedmanually;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_trans_disc_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_total_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_address_line4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? order_fee_name1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sold_qty;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? fee_type2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_country;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? activity_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee4_login_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? taken_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_item_gift_pgm_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? hist_discount_reason3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? udf_float5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? order_disc_reason;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? deposit_available_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_sale_used_points_positive;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_perc1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? order_fee_type1_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? created_by;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf18;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_sale_total_based_disc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? ref_order_created_datetime;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? tax_rebate_persisted;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? fee_tax_included2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf6;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? vat_options;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? total_discount_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee1_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_rebate_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Coupon[]?coupons;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_address_line6;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_tax1_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? ref_order_balance_due;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_postal_code;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_subtotal;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? st_cuid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? over_tax_percent2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? order_discount_reason_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? return_subtotal_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area2_sales_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? udf_float3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_perc_reward_pgm_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_used_points_negative;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_address_line6;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf11;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? al_extract_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_amt2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area2_order_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_perc1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee2_full_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_item_redeem_multiplier;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee4_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_tax_area2_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_amt_manual_bdt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? manual_disc_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? given_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? gift_receipt_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf15;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_perc_reward_disc_perc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? from_centrals;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt1_no_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? due_amt_current;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? used_disc_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_fee_tax_perc1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area_sales_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_postal_code_extension;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? return_tax2_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? al_post_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_credit_card;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? current_store_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_item_redeem_pgm_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee2_login_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_fee_tax_amt1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? order_fee_tax_included1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_amt_no_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? discount_amount;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_total_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_foreign_check;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_fee_amt1_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? total_fee_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt1_bdt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_tax1_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? manual_order_disc_value;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? workstation_sequence_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? document_reference_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_perc5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_gift_certificate;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_date2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_total_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? bt_security_lvl;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_balance_for_total_redeem;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_alternate_id1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Discount[]?discounts;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ref_sale_tax_area_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? was_audited;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_total_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_date1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? lty_lvl_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ar_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? cashier_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_percentage;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee1_full_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_company_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_last_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? tender_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? post_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? cancel_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_tax_perc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? ref_order_order_doc_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_amt2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? udf_float1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? activity3_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? udf_float4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_company_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? order_ship_method_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_alternate_id2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? is_held;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_string3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_address_line2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? total_deposit_used;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf10;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? comment1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_fee_amt1_no_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? pos_flag1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt_returned1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_end_balance;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee1_orig_sbs_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? hist_discount_reason5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee2_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_item_redeem_pgm_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_total_shipping_amt_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? price_lvl_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_address_zip;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area2_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? return_subtotal;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? original_store_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_item_earn_pgm_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_rebate_available;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_perc2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_postal_code_extension;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee3_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? st_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? manual_order_disc_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? lty_total_earn_pgm_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? use_vat;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_tax2_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? detax_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom6;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? bt_suggested_discount_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee4_orig_sbs_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_order_earned_points_negative;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_total_shipping_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf8;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf18;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? workstation_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee5_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? pos_flag2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_traveler_check;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? has_deposit;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee5_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? return_tax1_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_amt_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? cancel_order;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf7;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? return_total_tax_amt_rounded;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? manual_order_disc_reason;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? original_store_code;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? drawer_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? fee_tax_included4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_discount_amount;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? disc_reason;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? order_shipping_tax_included;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? fiscal_document_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? store_code;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? cashier_orig_sbs_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? deposit_ref_doc_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? rounded_due_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_amt_manual_returned;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_total_earn_multiplier;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_tax1_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? customer_field;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? ref_order_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? override_max_disc_perc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_foreign_currency;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_address_line5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_perc4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_last_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? send_sale_copy;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? order_discount_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? total_item_count;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_first_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? discount_reason_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf12;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_start_balance;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? total_fee_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? notes_return;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? employee4_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf13;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_address_line3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_title;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? allow_tender_cash;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? bt_max_discount_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? reason_description;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_earned_points_negative;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_price_lvl_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? docallow_tender_check;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? notes_sale;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_order_earned_points_positive;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf13;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? bt_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Deposit[]?deposits;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_amt4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf16;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? fee_name4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_customer_lookup;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? workstation_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? order_document_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_total_redeem_multiplier;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? status;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? fee_type3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? cashier_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? order_tracking_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? st_security_lvl;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? fee_tax_included5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? send_sale_last_event;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_subtotal_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_perc3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_amt_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? fee_name2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_order_total_based_disc;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_address_line1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_balance_due;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_qty;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_title;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? currency_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_perc4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TaxBreak[]?tax_breaks;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? fee_type1_sid;

    [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
    [JsonConverter(typeof(SidConverter))]
    public long? fee_type2_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
    [JsonConverter(typeof(SidConverter))]
    public long? fee_type3_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
    [JsonConverter(typeof(SidConverter))]
    public long? fee_type4_sid;

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? ship_partial;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? doc_tender_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_amt4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? sale_total_tax_amt_rounded;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? st_detax_flag;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? comment2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_first_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? activity5_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_trans_disc_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_item_earn_multiplier;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? transaction_total_shipping_amt_no_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? fee_type1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? tax_area_percent;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? order_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_price_lvl_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? reason_code;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_used_points_positive;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? customer_po_number;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? send_sale_fulfillment;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee2_id;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? invoice_posted_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? deposit_amt_taken;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_udf2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? discount_percent_spread;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_alternate_id2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? total_line_item;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf9;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_info1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_amt1_with_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_total_earn_pgm_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_total_tax_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_amt_manual;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? total_fee_amt_no_tax;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? fee_tax_amt3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? shipping_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_address_line1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? cashier_login_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_primary_phone_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? lty_item_earn_pgm_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee5_orig_sbs_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? lty_central_status;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee5_login_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? subsidiary_uid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_udf2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? tax_area_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? cashier_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_info2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? hist_discount_amt5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_address_line2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_address_line5;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? delete_order_discount;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? tax_area2_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee2_orig_sbs_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? modified_by;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_postal_code;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_email;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_tax2_amt;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ordered_date;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? controller_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? store_uid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_earned_points;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_primary_phone_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? origin_application;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? employee4_full_name;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? hist_discount_reason1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? employee3_orig_sbs_no;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? order_shipping_amt_manual;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? lty_earned_points_positive;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_address_line4;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? bt_allowed_tenders;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? udf_string1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? st_customer_lookup;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? bt_ar_flag;


    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? refOrderNo { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? refSaleOrderNo { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? refSaleOrderNo2 { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? refOrderSid { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? refSaleOrderSid { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? refSaleStoreSid { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.Always)]
    public string? KeyValue { get; set; }


    public Invoice Clone()
    {
        var invoice = new Invoice()
        {
            activity2_percent = this.activity2_percent,
            activity3_percent = this.activity3_percent,
            activity4_percent = this.activity4_percent,
            activity5_percent = this.activity5_percent,
            activity_percent = this.activity_percent,
            allow_tender_cash = this.allow_tender_cash,
            allow_tender_credit_card = this.allow_tender_credit_card,
            allow_tender_debit_card = this.allow_tender_debit_card,
            allow_tender_foreign_check = this.allow_tender_foreign_check,
            allow_tender_foreign_currency = this.allow_tender_foreign_currency,
            allow_tender_gift_card = this.allow_tender_gift_card,
            allow_tender_gift_certificate = this.allow_tender_gift_certificate,
            allow_tender_traveler_check = this.allow_tender_traveler_check,
            al_extract_date = this.al_extract_date,
            al_post_date = this.al_post_date,
            archived = this.archived,
            ar_flag = this.ar_flag,
            bt_address_line1 = this.bt_address_line1,
            bt_address_line2 = this.bt_address_line2,
            bt_address_line3 = this.bt_address_line3,
            bt_address_line4 = this.bt_address_line4,
            bt_address_line5 = this.bt_address_line5,
            bt_address_line6 = this.bt_address_line6,
            bt_allowed_tenders = this.bt_allowed_tenders,
            bt_alternate_id1 = this.bt_alternate_id1,
            bt_alternate_id2 = this.bt_alternate_id2,
            bt_ar_flag = this.bt_ar_flag,
            bt_company_name = this.bt_company_name,
            bt_country = this.bt_country,
            bt_cuid = this.bt_cuid,
            bt_customer_lookup = this.bt_customer_lookup,
            bt_detax_flag = this.bt_detax_flag,
            bt_email = this.bt_email,
            bt_first_name = this.bt_first_name,
            bt_id = this.bt_id,
            bt_info = this.bt_info,
            bt_info1 = this.bt_info1,
            bt_info2 = this.bt_info2,
            bt_last_name = this.bt_last_name,
            bt_max_discount_percent = this.bt_max_discount_percent,
            bt_postal_code = this.bt_postal_code,
            bt_postal_code_extension = this.bt_postal_code_extension,
            bt_price_lvl = this.bt_price_lvl,
            bt_price_lvl_name = this.bt_price_lvl_name,
            bt_primary = this.bt_primary,
            bt_primary_phone_no = this.bt_primary_phone_no,
            bt_security_lvl = this.bt_security_lvl,
            bt_suggested_discount_percent = this.bt_suggested_discount_percent,
            bt_tax_area2_name = this.bt_tax_area2_name,
            bt_tax_area_name = this.bt_tax_area_name,
            bt_title = this.bt_title,
            bt_udf1 = this.bt_udf1,
            bt_udf10 = this.bt_udf10,
            bt_udf11 = this.bt_udf11,
            bt_udf12 = this.bt_udf12,
            bt_udf13 = this.bt_udf13,
            bt_udf14 = this.bt_udf14,
            bt_udf15 = this.bt_udf15,
            bt_udf16 = this.bt_udf16,
            bt_udf17 = this.bt_udf17,
            bt_udf18 = this.bt_udf18,
            bt_udf2 = this.bt_udf2,
            bt_udf3 = this.bt_udf3,
            bt_udf4 = this.bt_udf4,
            bt_udf5 = this.bt_udf5,
            bt_udf6 = this.bt_udf6,
            bt_udf7 = this.bt_udf7,
            bt_udf8 = this.bt_udf8,
            bt_udf9 = this.bt_udf9,
            cancel_date = this.cancel_date,
            cancel_order = this.cancel_order,
            cashier_full_name = this.cashier_full_name,
            cashier_id = this.cashier_id,
            cashier_login_name = this.cashier_login_name,
            cashier_name = this.cashier_name,
            cashier_orig_sbs_no = this.cashier_orig_sbs_no,
            cashier_sid = this.cashier_sid,
            comment1 = this.comment1,
            comment2 = this.comment2,
            controller_number = this.controller_number,
            controller_sid = this.controller_sid,
            coupons = this.coupons,
            createdby_employeeid = this.createdby_employeeid,
            created_by = this.created_by,
            created_datetime = this.created_datetime,
            currency_name = this.currency_name,
            current_store_sid = this.current_store_sid,
            custom0 = this.custom0,
            custom1 = this.custom1,
            custom2 = this.custom2,
            custom3 = this.custom3,
            custom4 = this.custom4,
            custom5 = this.custom5,
            custom6 = this.custom6,
            custom7 = this.custom7,
            custom8 = this.custom8,
            custom9 = this.custom9,
            customer_field = this.customer_field,
            customer_po_number = this.customer_po_number,
            custom_flag = this.custom_flag,
            delete_discount = this.delete_discount,
            delete_order_discount = this.delete_order_discount,
            deposits = null,
            deposit_amt_required = this.deposit_amt_required,
            deposit_amt_taken = this.deposit_amt_taken,
            deposit_available_amt = this.deposit_available_amt,
            deposit_ref_doc_sid = this.deposit_ref_doc_sid,
            detax_amount = this.detax_amount,
            detax_flag = this.detax_flag,
            detax_flag_manually = this.detax_flag_manually,
            discounts = null,
            discount_amount = this.discount_amount,
            discount_perc = this.discount_perc,
            discount_percent_spread = this.discount_percent_spread,
            discount_reason_name = this.discount_reason_name,
            discount_type = this.discount_type,
            disc_reason = this.disc_reason,
            docallow_tender_check = this.docallow_tender_check,
            document_number = this.document_number,
            document_reference_number = this.document_reference_number,
            doc_tender_type = this.doc_tender_type,
            drawer_number = this.drawer_number,
            due_amt = this.due_amt,
            due_amt_current = this.due_amt_current,
            eft_invoice_number = this.eft_invoice_number,
            elapsed_time = this.elapsed_time,
            employee1_full_name = this.employee1_full_name,
            employee1_id = this.employee1_id,
            employee1_login_name = this.employee1_login_name,
            employee1_name = this.employee1_name,
            employee1_orig_sbs_no = this.employee1_orig_sbs_no,
            employee1_sid = this.employee1_sid,
            employee2_full_name = this.employee2_full_name,
            employee2_id = this.employee2_id,
            employee2_login_name = this.employee2_login_name,
            employee2_name = this.employee2_name,
            employee2_orig_sbs_no = this.employee2_orig_sbs_no,
            employee2_sid = this.employee2_sid,
            employee3_full_name = this.employee3_full_name,
            employee3_id = this.employee3_id,
            employee3_login_name = this.employee3_login_name,
            employee3_name = this.employee3_name,
            employee3_orig_sbs_no = this.employee3_orig_sbs_no,
            employee3_sid = this.employee3_sid,
            employee4_full_name = this.employee4_full_name,
            employee4_id = this.employee4_id,
            employee4_login_name = this.employee4_login_name,
            employee4_name = this.employee4_name,
            employee4_orig_sbs_no = this.employee4_orig_sbs_no,
            employee4_sid = this.employee4_sid,
            employee5_full_name = this.employee5_full_name,
            employee5_id = this.employee5_id,
            employee5_login_name = this.employee5_login_name,
            employee5_name = this.employee5_name,
            employee5_orig_sbs_no = this.employee5_orig_sbs_no,
            employee5_sid = this.employee5_sid,
            exchange_qty = this.exchange_qty,
            fee_amt1 = this.fee_amt1,
            fee_amt1_bdt = this.fee_amt1_bdt,
            fee_amt1_no_tax = this.fee_amt1_no_tax,
            fee_amt1_with_tax = this.fee_amt1_with_tax,
            fee_amt2 = this.fee_amt2,
            fee_amt3 = this.fee_amt3,
            fee_amt4 = this.fee_amt4,
            fee_amt5 = this.fee_amt5,
            fee_amt_returned1 = this.fee_amt_returned1,
            fee_name1 = this.fee_name1,
            fee_name2 = this.fee_name2,
            fee_name3 = this.fee_name3,
            fee_name4 = this.fee_name4,
            fee_name5 = this.fee_name5,
            fee_tax_amt1 = this.fee_tax_amt1,
            fee_tax_amt2 = this.fee_tax_amt2,
            fee_tax_amt3 = this.fee_tax_amt3,
            fee_tax_amt4 = this.fee_tax_amt4,
            fee_tax_amt5 = this.fee_tax_amt5,
            fee_tax_included1 = this.fee_tax_included1,
            fee_tax_included2 = this.fee_tax_included2,
            fee_tax_included3 = this.fee_tax_included3,
            fee_tax_included4 = this.fee_tax_included4,
            fee_tax_included5 = this.fee_tax_included5,
            fee_tax_perc1 = this.fee_tax_perc1,
            fee_tax_perc2 = this.fee_tax_perc2,
            fee_tax_perc3 = this.fee_tax_perc3,
            fee_tax_perc4 = this.fee_tax_perc4,
            fee_tax_perc5 = this.fee_tax_perc5,
            fee_type1 = this.fee_type1,
            fee_type1_sid = this.fee_type1_sid,
            fee_type2 = this.fee_type2,
            fee_type3 = this.fee_type3,
            fee_type4 = this.fee_type4,
            fee_type5 = this.fee_type5,
            fiscal_document_number = this.fiscal_document_number,
            from_centrals = this.from_centrals,
            gift_receipt_type = this.gift_receipt_type,
            given_amt = this.given_amt,
            gl_flag = this.gl_flag,
            has_deposit = this.has_deposit,
            has_return = this.has_return,
            has_sale = this.has_sale,
            hist_discount_amt1 = this.hist_discount_amt1,
            hist_discount_amt2 = this.hist_discount_amt2,
            hist_discount_amt3 = this.hist_discount_amt3,
            hist_discount_amt4 = this.hist_discount_amt4,
            hist_discount_amt5 = this.hist_discount_amt5,
            hist_discount_perc1 = this.hist_discount_perc1,
            hist_discount_perc2 = this.hist_discount_perc2,
            hist_discount_perc3 = this.hist_discount_perc3,
            hist_discount_perc4 = this.hist_discount_perc4,
            hist_discount_perc5 = this.hist_discount_perc5,
            hist_discount_reason1 = this.hist_discount_reason1,
            hist_discount_reason2 = this.hist_discount_reason2,
            hist_discount_reason3 = this.hist_discount_reason3,
            hist_discount_reason4 = this.hist_discount_reason4,
            hist_discount_reason5 = this.hist_discount_reason5,
            invoice_posted_date = this.invoice_posted_date,
            is_held = this.is_held,
            items = null,
            KeyValue = this.KeyValue,
            lty_balance_for_item_redeem = this.lty_balance_for_item_redeem,
            lty_balance_for_total_redeem = this.lty_balance_for_total_redeem,
            lty_central_status = this.lty_central_status,
            lty_earned_points = this.lty_earned_points,
            lty_earned_points_negative = this.lty_earned_points_negative,
            lty_earned_points_positive = this.lty_earned_points_positive,
            lty_end_balance = this.lty_end_balance,
            lty_gift_amt = this.lty_gift_amt,
            lty_item_earn_multiplier = this.lty_item_earn_multiplier,
            lty_item_earn_pgm_name = this.lty_item_earn_pgm_name,
            lty_item_earn_pgm_sid = this.lty_item_earn_pgm_sid,
            lty_item_gift_pgm_name = this.lty_item_gift_pgm_name,
            lty_item_gift_pgm_sid = this.lty_item_gift_pgm_sid,
            lty_item_redeem_multiplier = this.lty_item_redeem_multiplier,
            lty_item_redeem_pgm_name = this.lty_item_redeem_pgm_name,
            lty_item_redeem_pgm_sid = this.lty_item_redeem_pgm_sid,
            lty_lvl_name = this.lty_lvl_name,
            lty_lvl_sid = this.lty_lvl_sid,
            lty_order_earned_points_negative = this.lty_order_earned_points_negative,
            lty_order_earned_points_positive = this.lty_order_earned_points_positive,
            lty_order_total_based_disc = this.lty_order_total_based_disc,
            lty_order_used_points_negative = this.lty_order_used_points_negative,
            lty_order_used_points_positive = this.lty_order_used_points_positive,
            lty_perc_reward_disc_amt = this.lty_perc_reward_disc_amt,
            lty_perc_reward_disc_perc = this.lty_perc_reward_disc_perc,
            lty_perc_reward_pgm_name = this.lty_perc_reward_pgm_name,
            lty_perc_reward_pgm_sid = this.lty_perc_reward_pgm_sid,
            lty_redeem_amt = this.lty_redeem_amt,
            lty_sale_earned_points_negative = this.lty_sale_earned_points_negative,
            lty_sale_earned_points_positive = this.lty_sale_earned_points_positive,
            lty_sale_total_based_disc = this.lty_sale_total_based_disc,
            lty_sale_used_points_negative = this.lty_sale_used_points_negative,
            lty_sale_used_points_positive = this.lty_sale_used_points_positive,
            lty_start_balance = this.lty_start_balance,
            lty_total_earn_multiplier = this.lty_total_earn_multiplier,
            lty_total_earn_pgm_name = this.lty_total_earn_pgm_name,
            lty_total_earn_pgm_sid = this.lty_total_earn_pgm_sid,
            lty_total_redeem_multiplier = this.lty_total_redeem_multiplier,
            lty_total_redeem_pgm_name = this.lty_total_redeem_pgm_name,
            lty_total_redeem_pgm_sid = this.lty_total_redeem_pgm_sid,
            lty_used_points = this.lty_used_points,
            lty_used_points_negative = this.lty_used_points_negative,
            lty_used_points_positive = this.lty_used_points_positive,
            manual_disc_reason = this.manual_disc_reason,
            manual_disc_type = this.manual_disc_type,
            manual_disc_value = this.manual_disc_value,
            manual_order_disc_reason = this.manual_order_disc_reason,
            manual_order_disc_type = this.manual_order_disc_type,
            manual_order_disc_value = this.manual_order_disc_value,
            modifiedby_employeeid = this.modifiedby_employeeid,
            modified_by = this.modified_by,
            modified_datetime = this.modified_datetime,
            notes_general = this.notes_general,
            notes_lostdoc = this.notes_lostdoc,
            notes_order = this.notes_order,
            notes_return = this.notes_return,
            notes_sale = this.notes_sale,
            ordered_date = this.ordered_date,
            order_balance_due = this.order_balance_due,
            order_changed_flag = this.order_changed_flag,
            order_discount_amount = this.order_discount_amount,
            order_discount_perc = this.order_discount_perc,
            order_discount_reason_name = this.order_discount_reason_name,
            order_discount_type = this.order_discount_type,
            order_disc_reason = this.order_disc_reason,
            order_document_number = this.order_document_number,
            order_due_date = this.order_due_date,
            order_fee_amt1 = this.order_fee_amt1,
            order_fee_amt1_bdt = this.order_fee_amt1_bdt,
            order_fee_amt1_no_tax = this.order_fee_amt1_no_tax,
            order_fee_amt1_with_tax = this.order_fee_amt1_with_tax,
            order_fee_name1 = this.order_fee_name1,
            order_fee_tax_amt1 = this.order_fee_tax_amt1,
            order_fee_tax_included1 = this.order_fee_tax_included1,
            order_fee_tax_perc1 = this.order_fee_tax_perc1,
            order_fee_type1 = this.order_fee_type1,
            order_fee_type1_sid = this.order_fee_type1_sid,
            order_fulfilling_amt = this.order_fulfilling_amt,
            order_qty = this.order_qty,
            order_quantity_filled = this.order_quantity_filled,
            order_shipping_amt = this.order_shipping_amt,
            order_shipping_amt_manual = this.order_shipping_amt_manual,
            order_shipping_amt_manual_bdt = this.order_shipping_amt_manual_bdt,
            order_shipping_amt_manual_used =this.order_shipping_amt_manual_used,
            order_shipping_amt_no_tax = this.order_shipping_amt_no_tax,
            order_shipping_amt_with_tax = this.order_shipping_amt_with_tax,
            order_shipping_percentage = this.order_shipping_percentage,
            order_shipping_sid = this.order_shipping_sid,
            order_shipping_tax_amt = this.order_shipping_tax_amt,
            order_shipping_tax_included = this.order_shipping_tax_included,
            order_shipping_tax_perc = this.order_shipping_tax_perc,
            order_ship_method = this.order_ship_method,
            order_ship_method_id = this.order_ship_method_id,
            order_ship_method_sid = this.order_ship_method_sid,
            order_status = this.order_status,
            order_subtotal = this.order_subtotal,
            order_subtotal_with_tax = this.order_subtotal_with_tax,
            order_tax1_amt = this.order_tax1_amt,
            order_tax2_amt = this.order_tax2_amt,
            order_total_amt = this.order_total_amt,
            order_total_tax_amt = this.order_total_tax_amt,
            order_tracking_number = this.order_tracking_number,
            order_trans_disc_amt = this.order_trans_disc_amt,
            order_trans_disc_amt_used = this.order_trans_disc_amt_used,
            order_type = this.order_type,
            original_store_code = this.original_store_code,
            original_store_number = this.original_store_number,
            original_store_uid = this.original_store_uid,
            origin_application = this.origin_application,
            override_max_disc_perc = this.override_max_disc_perc,
            over_tax_percent = this.over_tax_percent,
            over_tax_percent2 = this.over_tax_percent2,
            post_date = this.post_date,
            pos_flag1 = this.pos_flag1,
            pos_flag2 = this.pos_flag2,
            pos_flag3 = this.pos_flag3,
            price_lvl = this.price_lvl,
            price_lvl_name = this.price_lvl_name,
            promo_gd_modifiedmanually = this.promo_gd_modifiedmanually,
            reason_code = this.reason_code,
            reason_description = this.reason_description,
            receipt_type = this.receipt_type,
            refOrderCashier = this.refOrderCashier,
            refOrderEmpl1 = this.refOrderEmpl1,
            refOrderNo = this.refOrderNo,
            refOrderSid = this.refOrderSid,
            refSaleCashier = this.refSaleCashier,
            refSaleEmpl1 = this.refSaleEmpl1,
            refSaleEmpl2 = this.refSaleEmpl2,
            refSaleOrderNo = this.refSaleOrderNo,
            refSaleOrderNo2 = this.refSaleOrderNo2,
            refSaleOrderSid = this.refSaleOrderSid,
            refSaleStoreSid = this.refSaleStoreSid,
            refund_document_sid = this.refund_document_sid,
            ref_order_balance_due = this.ref_order_balance_due,
            ref_order_created_datetime = this.ref_order_created_datetime,
            ref_order_doc_no = this.ref_order_doc_no,
            ref_order_order_doc_no = this.ref_order_order_doc_no,
            ref_order_sid = this.ref_order_sid,
            ref_order_tax_area_name = this.ref_order_tax_area_name,
            ref_sale_created_datetime = this.ref_sale_created_datetime,
            ref_sale_doc_no = this.ref_sale_doc_no,
            ref_sale_sid = this.ref_sale_sid,
            ref_sale_tax_area_name = this.ref_sale_tax_area_name,
            return_qty = this.return_qty,
            return_subtotal = this.return_subtotal,
            return_subtotal_with_tax = this.return_subtotal_with_tax,
            return_tax1_amt = this.return_tax1_amt,
            return_tax2_amt = this.return_tax2_amt,
            return_total_tax_amt = this.return_total_tax_amt,
            return_total_tax_amt_rounded = this.return_total_tax_amt_rounded,
            rounded_due_amt = this.rounded_due_amt,
            rounding_offset = this.rounding_offset,
            row_version = this.row_version,
            sale_subtotal = this.sale_subtotal,
            sale_subtotal_with_tax = this.sale_subtotal_with_tax,
            sale_tax1_amt = this.sale_tax1_amt,
            sale_tax2_amt = this.sale_tax2_amt,
            sale_total_amt = this.sale_total_amt,
            sale_total_tax_amt = this.sale_total_tax_amt,
            sale_total_tax_amt_rounded = this.sale_total_tax_amt_rounded,
            sale_trans_disc_amt = this.sale_trans_disc_amt,
            send_sale_copy = this.send_sale_copy,
            send_sale_fulfillment = this.send_sale_fulfillment,
            send_sale_last_error = this.send_sale_last_error,
            send_sale_last_event = this.send_sale_last_event,
            send_sale_status = this.send_sale_status,
            shipping_amt = this.shipping_amt,
            shipping_amt_manual = this.shipping_amt_manual,
            shipping_amt_manual_bdt = this.shipping_amt_manual_bdt,
            shipping_amt_manual_returned = this.shipping_amt_manual_returned,
            shipping_amt_no_tax = this.shipping_amt_no_tax,
            shipping_amt_with_tax = this.shipping_amt_with_tax,
            shipping_percentage = this.shipping_percentage,
            shipping_sid = this.shipping_sid,
            shipping_tax_amt = this.shipping_tax_amt,
            shipping_tax_included = this.shipping_tax_included,
            shipping_tax_percentage = this.shipping_tax_percentage,
            ship_date = this.ship_date,
            ship_method = this.ship_method,
            ship_method_id = this.ship_method_id,
            ship_method_sid = this.ship_method_sid,
            ship_partial = this.ship_partial,
            ship_priority = this.ship_priority,
            sid = this.sid,
            sold_qty = this.sold_qty,
            so_cancel_flag = this.so_cancel_flag,
            so_deposit_amt = this.so_deposit_amt,
            so_deposit_amt_paid = this.so_deposit_amt_paid,
            status = this.status,
            store_address_line1 = this.store_address_line1,
            store_address_line2 = this.store_address_line2,
            store_address_line3 = this.store_address_line3,
            store_address_line4 = this.store_address_line4,
            store_address_line5 = this.store_address_line5,
            store_address_line6 = this.store_address_line6,
            store_address_zip = this.store_address_zip,
            store_code = this.store_code,
            store_name = this.store_name,
            store_number = this.store_number,
            store_phone1 = this.store_phone1,
            store_phone2 = this.store_phone2,
            store_uid = this.store_uid,
            st_address_line1 = this.st_address_line1,
            st_address_line2 = this.st_address_line2,
            st_address_line3 = this.st_address_line3,
            st_address_line4 = this.st_address_line4,
            st_address_line5 = this.st_address_line5,
            st_address_line6 = this.st_address_line6,
            st_alternate_id1 = this.st_alternate_id1,
            st_alternate_id2 = this.st_alternate_id2,
            st_company_name = this.st_company_name,
            st_country = this.st_country,
            st_countryname = this.st_countryname,
            st_cuid = this.st_cuid,
            st_customer_lookup = this.st_customer_lookup,
            st_detax_flag = this.st_detax_flag,
            st_email = this.st_email,
            st_first_name = this.st_first_name,
            st_id = this.st_id,
            st_info = this.st_info,
            st_last_name = this.st_last_name,
            st_postal_code = this.st_postal_code,
            st_postal_code_extension = this.st_postal_code_extension,
            st_price_lvl = this.st_price_lvl,
            st_price_lvl_name = this.st_price_lvl_name,
            st_primary = this.st_primary,
            st_primary_phone_no = this.st_primary_phone_no,
            st_security_lvl = this.st_security_lvl,
            st_tax_area2_name = this.st_tax_area2_name,
            st_tax_area_name = this.st_tax_area_name,
            st_title = this.st_title,
            st_udf1 = this.st_udf1,
            st_udf10 = this.st_udf10,
            st_udf11 = this.st_udf11,
            st_udf12 = this.st_udf12,
            st_udf13 =this.st_udf13,
            st_udf14 = this.st_udf14,
            st_udf15 = this.st_udf15,
            st_udf16 = this.st_udf16,
            st_udf17 = this.st_udf17,
            st_udf18 = this.st_udf18,
            st_udf2 = this.st_udf2,
            st_udf3 = this.st_udf3,
            st_udf4 = this.st_udf4,
            st_udf5 = this.st_udf5,
            st_udf6 = this.st_udf6,
            st_udf7 = this.st_udf7,
            st_udf8 = this.st_udf8,
            st_udf9 = this.st_udf9,
            subsidiary_name = this.subsidiary_name,
            subsidiary_number = this.subsidiary_number,
            subsidiary_uid = this.subsidiary_uid,
            taken_amt = this.taken_amt,
            tax_area2_amt = this.tax_area2_amt,
            tax_area2_name = this.tax_area2_name,
            tax_area2_order_tax_amt = this.tax_area2_order_tax_amt,
            tax_area2_percent = this.tax_area2_percent,
            tax_area2_sales_tax_amt = this.tax_area2_sales_tax_amt,
            tax_area_amt = this.tax_area_amt,
            tax_area_name = this.tax_area_name,
            tax_area_order_tax_amt = this.tax_area_order_tax_amt,
            tax_area_percent = this.tax_area_percent,
            tax_area_sales_tax_amt = this.tax_area_sales_tax_amt,
            tax_breaks = this.tax_breaks,
            tax_rebate_amt = this.tax_rebate_amt,
            tax_rebate_available = this.tax_rebate_available,
            tax_rebate_percent = this.tax_rebate_percent,
            tax_rebate_persisted = this.tax_rebate_persisted,
            tenant_sid = this.tenant_sid,
            tenders = null,
            tender_name = this.tender_name,
            till_name = this.till_name,
            till_sid = this.till_sid,
            total_deposit_taken = this.total_deposit_taken,
            total_deposit_used = this.total_deposit_used,
            total_discount_amt = this.total_discount_amt,
            total_fee_amt = this.total_fee_amt,
            total_fee_amt_no_tax = this.total_fee_amt_no_tax,
            total_fee_tax_amt = this.total_fee_tax_amt,
            total_item_count = this.total_item_count,
            total_line_item = this.total_line_item,
            tracking_number = this.tracking_number,
            transaction_subtotal = this.transaction_subtotal,
            transaction_subtotal_with_tax = this.transaction_subtotal_with_tax,
            transaction_tax1_amt = this.transaction_tax1_amt,
            transaction_tax2_amt = this.transaction_tax2_amt,
            transaction_total_amt = this.transaction_total_amt,
            transaction_total_shipping_amt_no_tax = this.transaction_total_shipping_amt_no_tax,
            transaction_total_shipping_amt_with_tax = this.transaction_total_shipping_amt_with_tax,
            transaction_total_shipping_tax = this.transaction_total_shipping_tax,
            transaction_total_tax_amt = this.transaction_total_tax_amt,
            udf_clob1 = this.udf_clob1,
            udf_date1 = this.udf_date1,
            udf_date2 = this.udf_date2,
            udf_date3 = this.udf_date3,
            udf_float1 = this.udf_float1,
            udf_float2 = this.udf_float2,
            udf_float3 = this.udf_float3,
            udf_float4 = this.udf_float4,
            udf_float5 = this.udf_float5,
            udf_string1 = this.udf_string1,
            udf_string2 = this.udf_string2,
            udf_string3 = this.udf_string3,
            udf_string4 = this.udf_string4,
            udf_string5 = this.udf_string5,
            used_disc_amt = this.used_disc_amt,
            used_fee_amt1 = this.used_fee_amt1,
            used_shipping_amt = this.used_shipping_amt,
            used_subtotal = this.used_subtotal,
            used_tax = this.used_tax,
            use_vat = this.use_vat,
            vat_options = this.vat_options,
            was_audited = this.was_audited,
            workstation_name = this.workstation_name,
            workstation_number = this.workstation_number,
            workstation_sequence_number = this.workstation_sequence_number,
            workstation_uid = this.workstation_uid
        };

        if (this.deposits != null) {
            var deps = new List<Deposit>();
            foreach (var dep in this.deposits) {
                deps.Add(new Deposit());
            }
            invoice.deposits = deps.ToArray();
        }

        if (this.discounts != null) {
            var discs = new List<Discount>();
            foreach (var disc in this.discounts) {
                discs.Add(disc.Clone());

            }
            invoice.discounts = discs.ToArray();
        }

        if (this.items != null) {
            invoice.items = new List<InvoiceItem>();
            foreach (var item in this.items) {
                invoice.items.Add(item.Clone());
            }
        }

        if (this.tenders != null) {
            invoice.tenders = new List<InvoiceTender>();
            foreach (var tender in this.tenders) {
                invoice.tenders.Add(tender.Clone());
            }
        }


        return invoice;

    }
}


public class Coupon
{

}


public class Deposit
{

}

public class TaxBreak
{

}


public class InvoicePost
{
    public string? origin_application = "RProPrismWeb";
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? created_datetime;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? comment1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? comment2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? pos_flag1;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? pos_flag2;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? pos_flag3;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? ship_method_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonConverter(typeof(SidConverter))]
    public long? order_ship_method_sid;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? manual_disc_type;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public decimal? manual_disc_value;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? manual_disc_reason;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? manual_order_disc_reason;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? status;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? custom0;

    public InvoicePost() { }
    public InvoicePost(DateTime? created, string? comment1, string? comment2, string? originApplication = null, string? custom0 = null)
    {
        created_datetime = created;
        this.comment1 = comment1; 
        this.comment2 = comment2;
        this.origin_application = originApplication;
        this.custom0 = custom0; 
    }
}

public class InvoiceUpdate
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? status;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? modified_datetime;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? post_date;
    //[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    //public DateTime? invoice_posted_date;
    public InvoiceUpdate() { }
    public InvoiceUpdate(int? status, DateTime? modified = null)
    {
        this.status = status;
        DateTime? mf = modified.HasValue ? new DateTime(
            modified.Value.Year,
            modified.Value.Month,
            modified.Value.Day,
            modified.Value.Hour,
            modified.Value.Minute,
            modified.Value.Second,
            DateTimeKind.Unspecified
            )
            : null;
        this.modified_datetime = mf;
        this.post_date = mf;
        //this.invoice_posted_date = mf;
    }
}

public class InvoiceResponse : Invoice
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? link;
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Hrefs? hrefs;
}

public class Hrefs
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? controller_sid;
}