<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PrismExtensionServices.Shared\PrismExtensionServices.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PpitConfig" Version="1.0.8" />
  </ItemGroup>

</Project>
